# Plateformes de donation supportees par GitHub
# Remplacez les valeurs par vos identifiants

# GitHub Sponsors (votre username GitHub)
github: ceeeeb

# Autres plateformes (decommenter et remplir selon vos comptes)
# patreon: votre_username
# ko_fi: votre_username
# buy_me_a_coffee: votre_username

# PayPal (lien paypal.me ou adresse email)
custom: ["https://paypal.me/Ceeeeb6566"]
